In [9]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression


# load the data
data = pd.read_csv('CarPrice_Assignment.csv')
data.head()

   car_ID  symboling                   CarName fueltype aspiration  ... horsepower peakrpm citympg highwaympg    price
0       1          3        alfa-romero giulia      gas        std  ...        111    5000      21         27  13495.0
1       2          3       alfa-romero stelvio      gas        std  ...        111    5000      21         27  16500.0
2       3          1  alfa-romero Quadrifoglio      gas        std  ...        154    5000      19         26  16500.0
3       4          2               audi 100 ls      gas        std  ...        102    5500      24         30  13950.0
4       5          2                audi 100ls      gas        std  ...        115    5500      18         22  17450.0

[5 rows x 26 columns]

In [10]:
# Drop unused 
data = data.drop('CarName', axis=1)
data.head()

   car_ID  symboling fueltype aspiration doornumber  ... horsepower peakrpm citympg  highwaympg    price
0       1          3      gas        std        two  ...        111    5000      21          27  13495.0
1       2          3      gas        std        two  ...        111    5000      21          27  16500.0
2       3          1      gas        std        two  ...        154    5000      19          26  16500.0
3       4          2      gas        std       four  ...        102    5500      24          30  13950.0
4       5          2      gas        std       four  ...        115    5500      18          22  17450.0

[5 rows x 25 columns]

In [11]:
data_with_dummies = pd.get_dummies(data, drop_first=True)
data_with_dummies.head()

   car_ID  symboling  wheelbase  carlength  ...  fuelsystem_mfi  fuelsystem_mpfi  fuelsystem_spdi  fuelsystem_spfi
0       1          3       88.6      168.8  ...           False             True            False            False
1       2          3       88.6      168.8  ...           False             True            False            False
2       3          1       94.5      171.2  ...           False             True            False            False
3       4          2       99.8      176.6  ...           False             True            False            False
4       5          2       99.4      176.6  ...           False             True            False            False

[5 rows x 45 columns]

In [20]:
# Assigning X and y
X = data_with_dummies.drop('price', axis=1)
y = data_with_dummies['price']


# Instantiate the model
reg = LinearRegression()
reg.fit(X,y)


# Creating creating the statistic summary
intercept = reg.intercept_
r_squared = reg.score(X,y)


print(intercept)
print(r_squared)

-44638.5444476953
0.9470071021212597